---
title: ""
params:
  topic: "test"
output:
  html_document:
    theme: flatly
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(DT)
library(readxl)
library(tidyverse)
library(highcharter)


topic_selected <- params$topic
st_dta <- read_excel("state_dta.xlsx",sheet = topic_selected)

knitr::knit_hooks$set(inline = function(x) { if(!is.numeric(x)){ x }else{ prettyNum(round(x,2), big.mark=",", digits=6) } })
#hcoptslang <- getOption("highcharter.lang")
#hcoptslang$thousandsSep <- ","
#options(highcharter.lang = hcoptslang)
```


## State Data on `r topic_selected`

```{r echo=FALSE, message=FALSE, warning=FALSE}
datatable(st_dta,extensions = 
            list("Buttons" = NULL, 'FixedColumns'= T, "Scroller"=T),
          rownames= FALSE, 
          options = list(
            dom = 'Brtip',
            buttons = c('copy', 'csv', 'excel'),
            scrollX = TRUE,
            lengthMenu = c(25, 50, 100), pageLength = 50,
            deferRender = TRUE,
            scrollY = 400,
            scroller = TRUE)) %>%
            formatCurrency(columns = colnames(st_dta),currency = "", interval = 3, mark = ",", digits=0)


```

